### ISSUE TITLE
error during connect: This error may indicate that the docker daemon is not running.: Get

### ISSUE THREAD

**Issue by saber13812002** [DanielNery/odoo-docker-compose-nginx-postgresql#2]
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dodoo-docker-compose-nginx-postgresql-main%22%3Atrue%7D%7D&limit=0": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by DanielNery** [comment]
Hi, @saber13812002 !

I fixed the issue by switch docker to windows containers, then switch docker to linux container again. I used docker desktop tool.

We can switch docker container by command line

    check windowns hiper-v
    go to path of docker
    run command: ./DockerCli.exe -SwitchDaemon

Hope it helpful!
